name: 'Checkout (no submodules)'
description: 'Checks out your repository without initializing or updating submodules'
inputs:
  repository:
    description: 'The repository to checkout'
    required: true
  ref:
    description: 'The ref to checkout'
    required: false
  token:
    description: 'The token to use when cloning the repository'
    required: false
runs:
  using: 'composite'
  steps:
    - name: 'Checkout repository'
      shell: bash
      run: |
        git clone --no-checkout --depth=1 --no-tags --progress -- ${{ inputs.repository }} .
        git checkout --progress --force -B ${{ inputs.ref }}
