name: "Checkout without submodules"
description: "Checkout a Git repository without initializing or updating submodules"
inputs:
  repository:
    description: "The repository to check out"
    required: true
  ref:
    description: "The Git reference to check out"
    required: false
  token:
    description: "A GitHub Token to authenticate with"
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout without submodules
      run: |
        git init
        git remote add origin ${{ inputs.repository }}
        git -c protocol.version=2 fetch --depth=1 --no-tags --progress origin +${{ inputs.ref }}:refs/remotes/origin/${{ inputs.ref }}
        git checkout --progress --force -B ${{ inputs.ref }} refs/remotes/origin/${{ inputs.ref }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GIT_TERMINAL_PROMPT: 0
